theme: jekyll-theme-minimal
title: People Insights Dashboard
description: A comprehensive employee performance management system
baseurl: "/people-insights"
url: "https://aniruddha28715.github.io"
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false 